### ISSUE TITLE
Eigen Analyse(diagram) Klasse

### ISSUE THREAD

**Issue by Kode13-True** [KeithVoorhelst/Groepswerk_MuzieklesPlatform#27]
Maak voor u eigen klasse de vernieuwde schetsen. Denk ook na wat er in uw UML klasse zou komen (velden, objecten, methoden...).
[FirstDraftCodePlan.MusiLeren.txt](https://app.gitkraken.com/api/glo/boards/5ffda89c6f04050011743e83/attachments/60016a801c54ef0011644b11)

[FirstDraftCodePlan.Instrument.txt](https://app.gitkraken.com/api/glo/boards/5ffda89c6f04050011743e83/attachments/60047f896f04050011761720)

**Comment by BartVanGucht** [comment]
Het is geëindigd in een notepad bestand, zodat iedereen het kan zien, na oeverloos lang aanmodderen met de zoveelste gedwonloadde software om UML's mee te maken.  Alle info betreffende software die wél goed leert op dat vlak is welkom, maar alleszins mijn exkuses dat het dus niet in het voorziene schema staat.
